import turtle as t #import 输入
t.speed(99)
t.screensize(400,400)  #screensize大小
t.pensize(3)         #begin开始     fill填入      end结束
t.pencolor('blue')
t.fillcolor('blue')
t.begin_fill()
t.goto(0,5)
for i in range(2):
    t.forward(100)
    t.right(90)
    t.forward(150)
    t.right(90)
t.end_fill()
t.penup()
t.goto(100,5)
t.pencolor('red')
t.fillcolor('red')
t.begin_fill()
t.pensize(3)
t.pendown()
for i in range(2):
    t.forward(100)
    t.right(90)
    t.forward(150)
    t.right(90)
t.end_fill()
t.penup()
t.goto(200,5)
t.pencolor('yellow')
t.fillcolor('yellow')
t.begin_fill()
t.pensize(3)
t.pendown()
for i in range(2):
    t.forward(100)
    t.right(90)
    t.forward(150)
    t.right(90)
t.end_fill()
t.done()